Implement (de)serializtion to/from 8-byte array
0xKanekiKen/rescue_prime pull request #12
Opened 2023-04-20 21:40 UTC by MaxMustermann2

Introduce function `to_bytes` which converts a FieldElement into an 8-byte big-endian array in constant time via byte shifting. Introduce function `from_bytes` which takes an 8-byte big-endian array as input and returns a FieldElement or an Error if the resulting number is greater than the prime of the field.

Closes #3

2023-04-21 07:22 UTC, 0xKanekiKen requested changes
Thanks for your work! I've left few nits below.

2023-04-21 07:22 UTC, 0xKanekiKen commented on src/field_element/errors.rs
> +pub enum FieldError {
We can create a generic `enum` for all possible errors rather than be speciifc to Field only. It could be something like this:
```
pub enum Error {
     InvalidValue(String)
     DivisionByZero(String)
     ...  
}
```

We might also need to move the `error` file outside of `field_element` module.

2023-04-21 07:22 UTC, 0xKanekiKen commented on src/field_element/errors.rs
> +            FieldError::InvalidValue => write!(f, "Invalid value"),
I would rather prefer to call it `DeserializationError` and update the error description accordingly.

2023-04-21 07:22 UTC, 0xKanekiKen commented on src/field_element/mod.rs
> +            | (arr[7] as u64);
same comment as before. We should use [`from_le_bytes`](https://doc.rust-lang.org/std/primitive.u64.html#method.from_le_bytes) as it must be more optimized.

2023-04-21 07:25 UTC, 0xKanekiKen commented on src/field_element/mod.rs
> +        ]
Although the implementation is correct, I'd prefer to use [`to_le_bytes`](https://doc.rust-lang.org/std/primitive.u64.html#method.to_le_bytes) which is specifically designed to convert integers into their little-endian byte representation. The Rust standard library implementation is likely optimized for the target platform and should perform better than the manual bit-shifting and casting done in the first implementation.

2023-04-24 20:26 UTC, 0xkanekiken approved these changes
Thanks! Looks good to me.

2023-04-24 20:26 UTC, merged